### ISSUE TITLE
TalentButtonTemplate was removed in 8.1.5.29718

### ISSUE THREAD

**Issue by Andy1210** [adamz01h/wow_peggle#11]
https://github.com/adamz01h/wow_peggle/blob/dcb7c9f32a7a0ec70d9d006adef8cb8f1c78449b/Peggle/Peggle.lua#L8241

ActionButtonTemplate can work instead but, the following are being nil
		t.rank = getglobal(t:GetName().."Rank");
		t.border = getglobal(t:GetName().."Slot");
		t.icon = getglobal(t:GetName().."IconTexture");
I'm not experienced in this, I don't know why they are nil on global (getglobal seems to be deprecated, but I'm getting the same with _G[t:GetName().."Rank"]. I'd dont know where they should come from, can you please tell me some info about it?

as a workaround I have just commented out the following: t.icon = getglobal(t:GetName().."IconTexture");
At least it made the game working again, the talent page is working as well, but the buttons doesn't show which talent is active.

**Comment by Andy1210** [comment]
I managed to fix it :) https://github.com/adamz01h/wow_peggle/pull/12/commits/9eddec9856d0b344b218a5d4b218643b7d532643

**Comment by adamz01h** [comment]
Able to reproduce, full dump from swatter.
Date: 2019-03-24 00:48:35
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Peggle\Peggle.lua line 8238:
   CreateFrame(): Couldn't find inherited node "TalentButtonTemplate"
Debug:
   [C]: CreateFrame()
   Peggle\Peggle.lua:8238: e()
   Peggle\Peggle.lua:8260:
      Peggle\Peggle.lua:8074
   Peggle\Peggle.lua:8782:
      Peggle\Peggle.lua:8739
   Peggle\Peggle.lua:11156: T()
   Peggle\Peggle.lua:11358: in main chunk
Locals:
(*temporary) = "Button"
(*temporary) = "PeggleTalent1"
(*temporary) = <unnamed> {
 0 = <userdata>
 background = <unnamed> {
 }
 node = <table> {
 }
}
(*temporary) = "TalentButtonTemplate"

AddOns:
  Swatter, v8.1.6241 (SwimmingSeadragon)
  Peggle, v1.04
  BlizRuntimeLib_enUS v8.1.5.80100 <none>
  (ck=63)

**Comment by adamz01h** [comment]
Resolved by 9eddec9
