### ISSUE TITLE
Cannot Access Peggle

### ISSUE THREAD

**Issue by civilCornball** [adamz01h/wow_peggle#27]
**Describe the bug**
I managed to remove the Peggle minimap icon, but there is no way to replace that icon if it is deleted. Nor is there any way to open Peggle via any other means.

**Comment by adamz01h** [comment]
do /peggle

**Comment by civilCornball** [comment]
There's the thing: I *did* that! No idea why it didn't work then.

That command isn't mentioned anywhere, by the way.
