### ISSUE TITLE
Brag to Party or Raid

### ISSUE THREAD

**Issue by adamz01h** [adamz01h/wow_peggle#3]
Date: 2016-09-19 15:00:08
ID: 1
Error occured in: Global
Count: 1
Message: ..\FrameXML\UIDropDownMenu.lua line 1047:
   attempt to index local 'frame' (a nil value)
Debug:
   ..\FrameXML\UIDropDownMenu.lua:1047: UIDropDownMenu_SetText()
   Peggle\Peggle.lua:2017: func()
   ..\FrameXML\UIDropDownMenu.lua:760: UIDropDownMenuButton_OnClick()

```
  [string "*:OnClick"]:1
```

Locals:
frame = nil
text = "Party"
(*temporary) = <table> {
 ContainerFrame5Item7 = ContainerFrame5Item7 {
 }

**Comment by DrytheSolthesis** [comment]
Please address this we aren't allowed to spam guild chat with brags so I tried to set up a custom channel for it to no avail.

**Comment by ZombieProtectionAgency** [comment]
I started to look into this but I have never touched LUA or WoW scripting before so I am a little nervous to commit a functional change.

It looks like when `l` gets called in the button click event `UIDROPDOWNMENU_OPEN_MENU` is `nil`. Changing that constant to `UIDropDownMenu_GetCurrentDropDown()` seems to resolve the issue.

I dont know the implications of this change, it was kind of a stab in the dark.

**Comment by adamz01h** [comment]
Have not been on wow for the last several months make a change on the local, if it works please submit a pull request for review. Thanks!

**Comment by adamz01h** [comment]
Fixed with commit 516b8c7f4113d643a8ccd69a157758d9f80a050e
