### ISSUE TITLE
Battle/Duel both seem non-functional

### ISSUE THREAD

**Issue by ZombieProtectionAgency** [adamz01h/wow_peggle#8]

**Comment by adamz01h** [comment]
Could you past the swatter logs on this? Is any created?

**Comment by ZombieProtectionAgency** [comment]
Again, sorry for the super late reply/update! 

To be honest I have never touched LUA or WoW scripting before my initial formatting commits. I dont remember seeing a swatter pop up for the Duel/Battle screens before, they just didnt work. This time I did receive a popup so I tracked down a couple moved globals and patched them.

That said, I had NO idea that a method could return a "table" and assign individual results to comma delimited variables. I dont believe I removed any of those during my first "indentation" commit but please keep an eye out if any abnormal functionality pops up.

As an aside, unrelated do this issue, I noticed you put me in the change log twice, both my github username and my real name. I had commited once locally for the bulk then a couple fixes via the github UI and i guess both showed up.

**Comment by adamz01h** [comment]
What would you like to go by, make the change and I will merge the update, Thanks!

**Comment by ZombieProtectionAgency** [comment]
Just ZombieProtectionAgency works. It looks like my desktop was actually misconfigured, I ended up committing one of my other changes under the wrong account. Sorry to clutter up the commit history/this issue! I think I have my desktop configured correctly now.

**Comment by Andy1210** [comment]
I fixed both Duel and Battle. I had to sacrifice the crossrealm functionality(It was not working anyway...). Now at least it will work for players on the same realms.
You can find the fix under my Fork. When I will finish all the changes I want, I will make a PR for you to this original repo.

**Comment by Andy1210** [comment]
PR is ready: https://github.com/adamz01h/wow_peggle/pull/15

**Comment by adamz01h** [comment]
Reopened and reverted merge. Could not get game to load with PR.

**Comment by adamz01h** [comment]
@Andy1210 I have created another branch to handle experimental changes, such as level editor and the decrypted levels. If you would be so kind, please create a PR with just this fix implemented for testing. Thanks for all the hard work!

**Comment by Andy1210** [comment]
Did you copy the Levels.lua in place as well when you tried it?

**Comment by Andy1210** [comment]
I have a big PR now to the development branch. I have put 3 comments on the Peggle.lua file to show what are the lines for the duel/battle fix. I don't really want to create a separate PR with only those.

**Comment by Andy1210** [comment]
I propose to merge the development branch to the master since its working perfectly there :)

**Comment by adamz01h** [comment]
Was resolved
